In [4]:
import pandas as pd
import os

# Coloque aqui o caminho para a pasta onde você descompactou seus logs
log_directory = './'


for filename in os.listdir(os.getcwd()):
    if ".log" in filename:
        log_file = filename # O nome do seu arquivo de log
        print(log_file)
        full_path = os.path.join(log_directory, log_file)
        
        # Este bloco de código abre o arquivo, encontra a linha #fields e extrai os nomes das colunas
        columns = []
        with open(full_path, 'r') as f:
            for line in f:
                if line.startswith('#fields'):
                    # Separa a linha por TAB e pega todos os nomes a partir do segundo elemento
                    columns = line.strip().split('\t')[1:]
                    break
        
        # --- LEITURA DO ARQUIVO COM PANDAS ---
        try:
            df_conn = pd.read_csv(
                full_path,
                sep='\t',          # Informamos que o separador é TAB
                names=columns,       # Fornecemos os nomes das colunas que extraímos
                comment='#',       # Ignora todas as linhas de metadados que começam com '#'
                header=None,       # Diz ao pandas que não há uma linha de cabeçalho nos dados que ele está lendo
                low_memory=False
            )
        
            print("Log lido com sucesso! O DataFrame está pronto.")
            print(f"Número de conexões capturadas: {len(df_conn)}")
            
            # Exibe as 5 primeiras linhas do DataFrame organizado
            print("\nAmostra do DataFrame:")
            display(df_conn.head())
            df_conn['attack_cat'] = "Normal"
            df_conn['label'] = 0
            df_conn.to_csv(filename + '.csv', index=False)
        
        except FileNotFoundError:
            print(f"Erro: Arquivo não encontrado em '{full_path}'. Verifique o caminho.")
        except Exception as e:
            print(f"Ocorreu um erro: {e}")

conn.17_34_37-18_00_00.log
Log lido com sucesso! O DataFrame está pronto.
Número de conexões capturadas: 64

Amostra do DataFrame:

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,...,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents,ip_proto
0,1.760550e+09,CE0BY73hxGHvQDuutl,192.168.255.158,5353,224.0.0.251,5353,udp,dns,15.767682,2532,...,T,T,0,D,8,2756,0,0,-,17
1,1.760550e+09,CMEs2ua3RUmEdoimi,192.168.255.158,5353,224.0.0.251,5353,udp,dns,-,-,...,T,T,0,D,1,478,0,0,-,17
2,1.760550e+09,CxLgaj1P8oQ63xzTzb,192.168.255.158,5353,224.0.0.251,5353,udp,dns,-,-,...,T,T,0,D,1,478,0,0,-,17
3,1.760550e+09,CLfB9280IuW23qAfh,192.168.255.118,51671,239.255.255.250,1900,udp,-,2.978194,680,...,T,T,0,D,4,792,0,0,-,17
4,1.760550e+09,CrNUOK1wBHJszGIe36,192.168.255.113,61511,224.0.0.252,5355,udp,dns,0.419987,60,...,T,T,0,D,2,116,0,0,-,17

conn.18_11_43-19_00_00.log
Log lido com sucesso! O DataFrame está pronto.
Número de conexões capturadas: 580

Amostra do DataFrame:

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,...,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents,ip_proto
0,1.760552e+09,C3m39B3sVUCxOT1ZDk,192.168.255.118,63029,239.255.255.250,1900,udp,-,2.969829,680,...,T,T,0,D,4,792,0,0,-,17
1,1.760552e+09,CanD8oIJU17wUiy12,192.168.255.118,50891,224.0.0.252,5355,udp,dns,0.412087,64,...,T,T,0,D,2,120,0,0,-,17
2,1.760552e+09,CSpjo84FVOh9ISNQh3,192.168.255.102,5353,224.0.0.251,5353,udp,dns,1.017126,86,...,T,T,0,D,2,142,0,0,-,17
3,1.760552e+09,CwHHbt2dLCfqYZReU4,0.0.0.0,68,255.255.255.255,67,udp,dhcp,-,-,...,T,T,0,D,1,338,0,0,-,17
4,1.760552e+09,CJ8YGu2aCpTSj5zxfa,192.168.255.158,1900,239.255.255.250,1900,udp,-,-,-,...,T,T,0,D,3,495,0,0,-,17

conn.19_00_00-20_00_00.log
Log lido com sucesso! O DataFrame está pronto.
Número de conexões capturadas: 848

Amostra do DataFrame:

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,...,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents,ip_proto
0,1.760555e+09,CNvFFM165mUvqUEiyg,192.168.255.112,65136,192.168.255.221,25888,tcp,-,0.037912,102692,...,T,T,0,ScADcF,80,105904,0,0,-,6
1,1.760555e+09,COi7Eh2XmgUtiKTHEg,192.168.255.112,65137,192.168.255.221,5376,tcp,-,0.023728,0,...,T,T,0,ScAdfFa,39,1572,7,79612,-,6
2,1.760555e+09,Critf94gpS3cQSNou7,192.168.255.112,65135,192.168.255.221,21,tcp,ftp,0.134176,99,...,T,T,0,ScADcF,13,631,0,0,-,6
3,1.760555e+09,CPEHCx1ofe9f7iSqEa,192.168.255.116,5353,224.0.0.251,5353,udp,dns,-,-,...,T,T,0,D,1,73,0,0,-,17
4,1.760555e+09,CYkvVP1uneBlZwh6ua,192.168.255.112,65163,192.168.255.221,80,tcp,http,0.020602,1025,...,T,T,0,ScADF,13,1557,0,0,-,6

conn.20_00_00-20_49_08.log
Log lido com sucesso! O DataFrame está pronto.
Número de conexões capturadas: 686

Amostra do DataFrame:

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,...,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents,ip_proto
0,1.760558e+09,C5lH9y3BdMuK0cY4th,192.168.255.112,51734,192.168.255.221,48044,tcp,-,0.026085,73648,...,T,T,0,ScADcF,58,75980,0,0,-,6
1,1.760558e+09,CbznzUQGn4Be3HYFb,192.168.255.112,51733,192.168.255.221,21,tcp,ftp,0.078593,99,...,T,T,0,ScADcF,13,631,0,0,-,6
2,1.760558e+09,CIi9373koHgGq8YjB3,192.168.255.112,51742,192.168.255.221,80,tcp,http,0.031714,1025,...,T,T,0,ScADF,13,1557,0,0,-,6
3,1.760558e+09,CWmuyF3j6EN01IiYFa,192.168.255.112,51765,192.168.255.221,80,tcp,http,0.030501,1025,...,T,T,0,ScADF,13,1557,0,0,-,6
4,1.760558e+09,Cx3Mjv2j2IQyp0AcCl,192.168.255.112,50169,192.168.255.221,32840,tcp,-,0.007924,0,...,T,T,0,ScAdFa,14,572,2,10300,-,6